Added initIdentityManager container to oidcclient-watcher pod.
IBM/ibm-iam-operator pull request #175
Opened 2020-09-01 12:35 UTC by pnpavan25

Added initIdentityManager container to oidcclient-watcher pod.

2020-09-02 05:13 UTC, posriniv requested changes

2020-09-02 05:13 UTC, posriniv commented on pkg/apis/operator/v1alpha1/oidcclientwatcher_types.go
> +	InitIdentityManager  InitIdentityManagerSpec  `json:"initIdentityManager"`
This will cause upgrade problems

2020-09-02 05:13 UTC, posriniv commented on deploy/crds/operator.ibm.com_v1alpha1_oidcclientwatcher_cr.yaml
> +  initIdentityManager:
This will cause upgrade problems

2020-09-02 05:13 UTC, posriniv commented on deploy/crds/operator.ibm.com_oidcclientwatchers_crd.yaml
> +            initIdentityManager:
This will cause upgrade problems

2020-09-03 08:28 UTC, pnpavan25 commented
@posriniv I have made changes as you suggested. Please review again. thanks!
Verified with both older and new CRD/CR, oidcclient-watcher deployment is working fine.

2020-09-03 22:29 UTC, pnpavan25 commented
@posriniv Thanks. I have made changes as you suggested and removed hardcoded image registry. Please review and approve. thanks!

2020-09-04 13:19 UTC, posriniv approved these changes
lgtm

2020-09-04 13:28 UTC, yannizhang2019 reviewed
Please make sure the upgrade is tested with this change

2020-09-04 13:40 UTC, pnpavan25 commented on pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
> +						{
If instance.Spec.OidcInitIdenityManager is nil, then I am creating InitContainer with default values.
So as part of new controller, the InitContainer will always added to oidcclient-watcher deployment.

2020-09-04 13:40 UTC, pnpavan25 commented on pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
> +		initContainerImageRegistry = instance.Spec.OidcInitIdentityManager.ImageRegistry
I think, as OidcInitIdenityManager is a struct, it will empty struct{} not nil after unmarshal.

2020-09-04 13:42 UTC, pnpavan25 commented
@yannizhang2019 Sure, we will test upgrade with these changes. Srini said, he will help in testing upgrade. thanks!

2020-09-04 13:52 UTC, pnpavan25 commented on pkg/apis/operator/v1alpha1/oidcclientwatcher_types.go
> +	InitIdentityManager  InitIdentityManagerSpec  `json:"initIdentityManager"`
Added omitempty.

2020-09-04 13:53 UTC, merged