Accept x-frame domain value in operand configuration
IBM/ibm-iam-operator pull request #205
Opened 2020-09-24 10:31 UTC by rashmi43

2020-09-24 17:19 UTC, rashmi43 commented
MCMP is handling it locally but we can decide whether to merge this or not for 3.5.4. If not we can do it for Q4.

2020-09-24 17:31 UTC, znhafeez commented
/lgtm

2020-09-24 17:32 UTC, znhafeez approved these changes

2020-09-25 03:19 UTC, yannizhang2019 approved these changes

2020-09-25 04:34 UTC, rashmi43 commented
@posriniv please review

2020-09-25 12:39 UTC, posriniv requested changes

2020-09-25 12:39 UTC, posriniv commented on pkg/apis/operator/v1alpha1/authentication_types.go
> +	XFrameDomain                string `json:"xframeDomain"`
@rashmi43 you must add `omitempty` here

2020-09-25 12:39 UTC, posriniv commented on pkg/controller/authentication/ingress.go
> +		xframeDomain = strings.Join([]string{"'ALLOW-FROM ", instance.Spec.Config.XFrameDomain, "'"}, "")
you can set a flag here here called ingressUpdateRequired and Update the corresponding ingress as we upate the configmap here https://github.com/IBM/ibm-iam-operator/blob/master/pkg/controller/authentication/configmap.go#L173-L178

2020-09-25 15:52 UTC, merged