update to 3.10.0
IBM/ibm-iam-operator pull request #322
Opened 2021-03-12 10:55 UTC by rashmi43

2021-03-12 15:06 UTC, posriniv requested changes

2021-03-12 15:06 UTC, posriniv commented on deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
> +  replaces: ibm-iam-operator.v3.9.1
please use 3.9.2 here

2021-03-15 09:29 UTC, rashmi43 commented on deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
> +  replaces: ibm-iam-operator.v3.9.1
updated

2021-03-15 09:31 UTC, posriniv approved these changes
lgtm

2021-03-15 13:27 UTC, yannizhang2019 approved these changes

2021-03-15 13:29 UTC, merged