Iam next
IBM/ibm-iam-operator pull request #507
Opened 2022-10-13 11:24 UTC by rashmi43

2022-11-14 13:28 UTC, rwhundley requested changes

2022-11-14 13:28 UTC, rwhundley commented on common/scripts/.githooks/make_lint-all.sh
> +make lint-scripts
Why is this changing? I would think that we want to lint everything as a default, and the script itself is called `make_lint-all.sh`.

2022-11-15 14:17 UTC, rashmi43 commented on pkg/controller/authentication/authentication_controller.go
> +	//csCfgAnnotationName := res.GetCsConfigAnnotation(instance.Namespace)
updated it

2022-11-15 14:43 UTC, rwhundley commented
/approve

2022-11-15 15:44 UTC, rwhundley approved these changes

2022-11-15 17:43 UTC, rwhundley approved these changes
/lgtm

2022-11-15 17:43 UTC, merged