Update ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
IBM/ibm-iam-operator pull request #510
Opened 2022-10-25 09:04 UTC by rashmi43

2022-10-28 18:17 UTC, rwhundley requested changes

2022-10-28 20:23 UTC, yannizhang2019 approved these changes

2022-10-31 10:51 UTC, rashmi43 commented on deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
> +            "imageTagPostfix": "3.10.0",
currently we have updated the code in manager and provider, for other repos we will take them as is now till we remove them

2022-10-31 10:52 UTC, rashmi43 commented on deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
> +              volumes:
we can add it as part of your watcher changes

2022-10-31 12:07 UTC, rwhundley approved these changes

2022-10-31 12:07 UTC, rwhundley commented on deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
> +              volumes:
Fair enough.

2022-10-31 13:38 UTC, rashmi43 commented
/lgtm

2022-10-31 14:03 UTC, merged