[INPROGRESS]consume postgresql configmap and secret deployed by odlm
IBM/ibm-iam-operator pull request #744
Opened 2024-02-08 15:15 UTC by Tirumalavasa

https://github.ibm.com/ibmprivatecloud/roadmap/issues/62210

2024-02-11 17:03 UTC, rwhundley requested changes

2024-02-11 17:03 UTC, rwhundley commented on controllers/operator/operandrequest.go
> +func (r *AuthenticationReconciler) checkCommonServiceExists(instance *operatorv1alpha1.Authentication) (exist bool) {
Given that the code isn't doing anything more than trying to create this CommonService CR if it doesn't already exist (versus actually performing comparisons to see if there is a change that needs to be made by the reconciler), breaking out a separate "check" function can be skipped - the logic should just try to create the resource and, if the resource already exists, api will give us back that error, which we can identify to know that there's no more work to do.

2024-02-19 18:30 UTC, rashmi43 approved these changes

2024-02-20 08:37 UTC, Tirumalavasa commented
Closing this PR, as this is taken care as part of https://github.com/IBM/ibm-iam-operator/pull/745

2024-02-20 08:37 UTC, closed without merging