Remove redundant endpoint - idauth
IBM/ibm-iam-operator pull request #848
Opened 2024-07-08 04:57 UTC by YangShyrMei

2024-07-09 10:50 UTC, Tirumalavasa approved these changes

2024-07-10 07:27 UTC, rashmi43 commented on controllers/operator/ingress.go
> +									Path:     "/oidc/endpoint",
we can remove this as well

2024-09-03 19:45 UTC, rwhundley requested changes
Requesting changes because I think this may be missing a chunk of the logic related to what @rashmi43 mentioned re: tokens and want to be sure that's not needed before this gets merged. It seems like the OIDC registration.json needs to be updated to use the new value set in controllers/operators/constants.go, and that JSON needs to be applied by re-running the Job that submits it, but I don't see anything related to that in here. I've also just added some testing around the Route reconciliation in the Authentication controller, so I'd imagine those will need to be updated as well.

2024-09-03 19:53 UTC, rwhundley commented
/test test ibm-iam-operator

2024-09-03 19:55 UTC, rwhundley commented
Ah, my mistake re: testing - missed that this was going into SC2. The comment re: test updates does not apply here, but the other parts of my review do.

2024-09-13 06:14 UTC, YangShyrMei commented
Will build a new pr with the different approach as used in https://github.com/IBM/ibm-iam-operator/pull/871

2024-09-13 06:14 UTC, closed without merging